Repository ssis-aa/generative-art-collaboration2022, pull requests merged in 2022-12, with the labels that each got.

#7 Is not avaliable patch 1
  art.js
Labels: bug, documentation

#13 Expanded documentation
  README.md
  docs/2022-12-07.png
  docs/2022-12-12.png
  docs/README.md
Labels: enhancement

#14 Enhance documentation
  README.md
  docs/2022-12-07.png
  docs/2022-12-12.png
  docs/README.md
Labels: documentation

#23 Image filter2
  art.js
Labels: enhancement

#28 the bubble filter finally works!
  art.js
Labels: enhancement

#31 update documentation v5
  README.md
  docs/2022-12-13.png
  docs/2022-12-21.png
  docs/2022-12-21b.png
  docs/README.md
Labels: documentation

#34 random-squares gets an update v5
  README.md
  docs/2022-12-21.png
  docs/2022-12-21b.png
  docs/README.md
Labels: documentation

#35 staged code from 6 days
  README.md
  art.js
  docs/2022-12-23.png
  docs/example.jpg
  docs/rotate_canvas.js
Labels: documentation, enhancement
